### ISSUE TITLE
Find a new name

### ISSUE THREAD

**Issue by phiberber** [phiberber/morpheus#1]
I decided to name the programming language "ian" as it is part of my surname. But I'm not a fan of naming something based on myself.

So that is why we need a new name for the programming language. Time to start from scratch!
Here are the two names I've thought of by now.

- Neve
- Ease

Please, if you have any suggestions. Comment here.

**Comment by phiberber** [comment]
Nive might be better than Neve

**Comment by gpeterin** [comment]
You can mix them, maybe "Eave"

**Comment by phiberber** [comment]
Eave might not be that good as it's an English word. Rust is an excellent example as to why programming languages should find unique names.

**Comment by gpeterin** [comment]
Well, if I choose, I would choose "Ease" it sounds professional, I liked it

**Comment by phiberber** [comment]
I've thought of some other names:

- Lift (May be too similar to Lyft)
- Quoll
- Serval

**Comment by phiberber** [comment]
Lift may be too similar to Lyft, which already is a popular brand.

**Comment by gpeterin** [comment]
I still prefer Ease

**Comment by phiberber** [comment]
Closing the issue, the new name is going to be Ease.

**Comment by buribu** [comment]
https://en.wikipedia.org/wiki/Ease_(programming_language)

**Comment by phiberber** [comment]
> https://en.wikipedia.org/wiki/Ease_(programming_language)

It is not much of a problem, seeing that the language is 31 years old. Probably no one currently codes anything using it nowadays. I do think though that some old people might find it confusing, imagine if brainfuck were initially called D... The name can still be changed but I don't have any idea of a name that fits better.

**Comment by gpeterin** [comment]
> https://en.wikipedia.org/wiki/Ease_(programming_language)

It's a too old language to care
